<?php /* \Admin\inc\tx\IFRS-SME-2018\BuildTxDB.inc

Taxonomy specific include for IFRS-SME-2018

https://www.ifrs.org/issued-standards/ifrs-taxonomy/ifrs-taxonomy-2018/#entry-points

History:
2018.11.08 Started

*/

$entryPointUrl = 'http://xbrl.ifrs.org/taxonomy/2018-03-16/ifrs_for_smes_doc_entry_point_2018-03-16.xsd';

$MissedScemasAA = [[6, 'http://www.xbrl.org/2006/ref-2006-02-27.xsd']]; # X => [SchemaId at which the missing schema is to be imported, url]

